inperium-corp/inperium-openapi

talk/talk-api.yaml

- https://blackbirdsoftware.atlassian.net/browse/INT-254

INT-254 Return call date in voicemails endpoint

---

README.md

Described the repo structure and added some notes about our API.

updated the Readme.md file

---

hub/hub-api.yaml

This pull request adds promotion codes to the create subscription endpoint in the Hub.

Feature/INA-133 Add promotion codes

---

talk/talk-api.yaml

Add the PhoneNumber.Name field

INT-303 INT-301 Allow to purchase multiple phone numbers at once

---

talk/talk-api.yaml

- https://blackbirdsoftware.atlassian.net/browse/INT-262

INT-262 Add toPhoneNumber field to the call entity

---

talk/talk-api.yaml

INT-274 [BE] API Endpoint for "calls by country" widget
INT-268 [BE] API Endpoint for "agent status" widget

[INT-273] [BE] API Endpoint for "calls leaderboard" widget

---

hub/hub-api.yaml
sell/sell-api.yaml

Added missing descriptions to hub-api.yaml
Fixed typo in Sell-api.yaml

Minor updates

---

sell/sell-api.yaml

This pull request fixes a bug in which the quote page does not have all the Infomation it needs to properly render.

Bugfix for Quote Model missing Information

---

obs/obs-api.yaml
talk/talk-api.yaml

Revert "INT-310 Migrate from OBS starter to OBS microservice (#125)"

---

sell/sell-api.yaml

Added examples for object models: company, companyRequest, contact, contactRequest, etc. - this is needed for API docs

Api examples

---

sell/sell-api.yaml

This pull request adds the attachments functionality to the deal entity. It was requested by several of our customers.

[INS-3257] Add attachments for the deal entity

---

hub/hub-api.yaml
lead-router/lead-router-api.yaml
message-center/message-center-api.yaml
sell/sell-api.yaml

I've updated some minor descriptions. Also, I've grabbed recent MC api changes and re-ordered endpoints alphabetically.

Misc description updates

---

hub/hub-api.yaml
lead-router/lead-router-api.yaml
message-center/message-center-api.yaml
obs/obs-api.yaml
sell/sell-api.yaml

I have replaced */* with application/json

Mics updates for api docs

---

sell/sell-api.yaml

Removed unused fields:
ActivityRequest.id
Company.activities
Contact.activities
Deal.activities

[INS-3262] [TECH] ActivityRequest object shouldn't have an id

---

sell/sell-api.yaml

Add new types of event activity for imported entities.

[INS-3304] [Import] "Entity Imported" activity type.

---

hub/hub-api.yaml

Tiny updates for balance endpoints

Minor updates for balance endpoints

---

hub/hub-api.yaml

Per Alex request, applied x-access: private to App settings

Applied private flag to App settings

---

talk/talk-api.yaml

Fixed /calls filtering, added a custom filter for missed and no answer calls

INT-489 Missed Calls strategic vision

---

README.md
sell/sell-api.yaml

Added a couple of examples for API docs, fixed small text issues.

Description updates for api docs

---

README.md
global-registry/global-registry-api.yaml
hub/hub-api.yaml
message-center/message-center-api.yaml

This pull request moves the global registry API from the microservice into our OpenAPI repository. I also cleaned the API a bit by giving the models more precise and accurate names. Additionally, I added endpoints to update and delete the regional mappings for users, tenants and API keys.

Global Registry API

---

sell/sell-api.yaml

* [INS-3337] [Contacts] On the contact table, the column with companies does not load data

Merge Dev to Qa

---

talk/talk-api.yaml

INT-230 Strict possible values for Contact email and phoneNumber types (WORK/PERSONAL/OTHER)

INT-230 Strict possible values for Contact email and phoneNumber types (WORK/PERSONAL/OTHER)

---

sell/sell-api.yaml

I have updated examples in sell-api.yaml (contacts, deals, companies).

Updating examples

---

talk/talk-api.yaml

Guys, I've found that these fields are NOT NULL in our database, so I fixed the API.

Fixed required fields for PhoneNumber and PhoneNumberRequest

---

sell/sell-api.yaml
talk/talk-api.yaml

I've updated descriptions for all Talk endpoints and components except for those marked as private (callbacks, regulatory bundles, etc.) Additionally, I've made some minor tweaks in Sell API descriptions (while working on Talk API, I found better wording and updated it everywhere).

Talk component descriptions

---

sell/sell-api.yaml

Changed parameter for the import. 
Parameters moved from URL to the request body.

[INS-3511] [Products] Import does not work

---

sell/sell-api.yaml

Hey, I've made some minor tweaks to API files to make them look better in our documentation.

Fixes for APi docs

---

talk/talk-api.yaml

* INT-629 Add idempotency key to the Talk endpoint portPhoneNumber

INT-629 Make Talk endpoint portPhoneNumber idempotent

---

hub/hub-api.yaml

This is just a small update to the 2fa endpoints to adapt them to the new sign up flow.

Small update for the 2fa endpoints
